source 'https://rubygems.org'

gem 'rack'
gem 'sinatra'
gem 'passbook'
gem 'activesupport'
gem 'rubyzip', '~> 1.0.0'
gem 'grocer'
gem 'commander'
gem 'terminal-table'
gem 'omniauth-github'
gem 'omniauth-openid'
gem 'omniauth-twitter'
